/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import useRotateRotor from "../../hooks/useRotateRotor";

export default function RLF(props) {
  const { group, nodes, materials } = useRotateRotor("/rLF.glb", true);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Rotor_CCW_01" position={[0.09, 0.02, 0.1]}>
          <mesh
            name="Plane014"
            castShadow
            receiveShadow
            geometry={nodes.Plane014.geometry}
            material={materials["Drone Carbon Fibre_Blades"]}
          />
          <mesh
            name="Plane014_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane014_1.geometry}
            material={materials["Drone Metal Shiny"]}
          />
          <mesh
            name="Plane014_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane014_2.geometry}
            material={materials["Drone Metal Black"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/rLF.glb");
