/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function CombatDrone(props) {
  const { nodes, materials } = useGLTF("/CombatDrone.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.15, 0]} scale={0.39}>
        <group
          position={[0.28, -0.15, 0.68]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={0.84}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere003.geometry}
            material={materials["Material.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere003_1.geometry}
            material={materials["drone.001"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/CombatDrone.glb");
