/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function CombatDroneSmooth(props) {
  const { nodes, materials } = useGLTF("/CombatDroneSmooth.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.11, 0.07, 0.26]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.33}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere003.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere003_1.geometry}
          material={materials["drone.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/CombatDroneSmooth.glb");
