/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import "./DroneDescription.scss";

import React, { useRef } from "react";
import { Html, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { animated, useSpring } from "@react-spring/three";
import { degToRad } from "three/src/math/MathUtils";

const Model = ({ nodes, materials }) => {
  return (
    <group
      position={[0.28, 1.16, 0.68]}
      rotation={[Math.PI, 0, Math.PI]}
      scale={0.64}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere003.geometry}
        material={materials["Material.013"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere003_1.geometry}
        material={materials["drone.001"]}
      />
    </group>
  );
};

export default function CombatDroneAutoSmooth({ hasInfo, ...props }) {
  const rotDelay = 10;

  const CombatDroneFull = useRef();

  useFrame(({ clock }) => {
    CombatDroneFull.current.position.y =
      0.03 * Math.sin(2 * clock.getElapsedTime());
  });

  const { nodes, materials } = useGLTF(
    `${import.meta.env.BASE_URL}CombatDroneAutoSmooth.glb`
  );

  const { CDASRot } = useSpring({
    from: { CDASRot: degToRad(0), delay: rotDelay },
    to: [
      {
        CDASRot: degToRad(90),
        delay: rotDelay,
      },
      {
        CDASRot: degToRad(2 * 90),
        delay: rotDelay,
      },
      {
        CDASRot: degToRad(3 * 90),
        delay: rotDelay,
      },
      {
        CDASRot: degToRad(4 * 90),
        delay: rotDelay,
      },
    ],
    config: {
      mass: 200,
      tension: 1000,
      friction: 500,
    },
  });

  return (
    <group {...props} dispose={null} ref={CombatDroneFull}>
      {hasInfo ? (
        <animated.group
          position={[-0.022, -0.35, 0]}
          scale={0.39}
          rotation-y={CDASRot}
        >
          <Html center>
            <div className="drone-description-container">
              <label htmlFor="text" className="drone-description-button">
                1
              </label>
              <p className="drone-description">
                Presenting the worlds most advanced combat drone. The combined
                power of its undestructible armor and the heavy caliber weapons
                make this the most dangerous combat drone out there
              </p>
            </div>
          </Html>
          <Model {...{ nodes, materials }} />
        </animated.group>
      ) : (
        <group position={[-0.022, -0.35, 0]} scale={0.39}>
          <Model {...{ nodes, materials }} />
        </group>
      )}
    </group>
  );
}

useGLTF.preload(`${import.meta.env.BASE_URL}CombatDroneAutoSmooth.glb`);
