/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import useRotateRotor from "./hooks/useRotateRotor";

export default function RLB(props) {
  const { group, nodes, materials } = useRotateRotor("/rLB.glb");

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Rotor_CW_02" position={[0.09, 0.02, -0.12]}>
          <mesh
            name="Plane016"
            castShadow
            receiveShadow
            geometry={nodes.Plane016.geometry}
            material={materials["Drone Carbon Fibre_Blades"]}
          />
          <mesh
            name="Plane016_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane016_1.geometry}
            material={materials["Drone Metal Shiny"]}
          />
          <mesh
            name="Plane016_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane016_2.geometry}
            material={materials["Drone Metal Black"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/rLB.glb");
