/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import useRotateRotor from "./hooks/useRotateRotor";

export default function RRB(props) {
  const { group, nodes, materials } = useRotateRotor("/rRB.glb", true);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Rotor_CCW_02" position={[-0.09, 0.02, -0.12]}>
          <mesh
            name="Plane015"
            castShadow
            receiveShadow
            geometry={nodes.Plane015.geometry}
            material={materials["Drone Carbon Fibre_Blades"]}
          />
          <mesh
            name="Plane015_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane015_1.geometry}
            material={materials["Drone Metal Shiny"]}
          />
          <mesh
            name="Plane015_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane015_2.geometry}
            material={materials["Drone Metal Black"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/rRB.glb");
