/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import useRotateRotor from "./hooks/useRotateRotor";

export default function RRF(props) {
  const { group, nodes, materials } = useRotateRotor("/rRF.glb");

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Rotor_CW_01" position={[-0.09, 0.02, 0.1]}>
          <mesh
            name="Plane013"
            castShadow
            receiveShadow
            geometry={nodes.Plane013.geometry}
            material={materials["Drone Carbon Fibre_Blades"]}
          />
          <mesh
            name="Plane013_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane013_1.geometry}
            material={materials["Drone Metal Shiny"]}
          />
          <mesh
            name="Plane013_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane013_2.geometry}
            material={materials["Drone Metal Black"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/rRF.glb");
